// Lista confirmada a partir das partes reais enviadas pelo Aldo (hino
// "Plena Paz" — Harpa 3). Timpano e bateria são instrumentos diferentes,
// por isso ficam em naipes separados em vez de um "Percussão" genérico.
export const NAIPES = {
  orquestra: [
    "Violino 1",
    "Violino 2",
    "Violino 3",
    "Violino Estudante",
    "Viola",
    "Violoncelo",
    "Contrabaixo",
    "Piano",
    "Flauta 1",
    "Flauta 2",
    "Flauta Estudante",
    "Clarinete 1",
    "Clarinete 2",
    "Saxofone Alto",
    "Saxofone Tenor",
    "Saxofone Barítono",
    "Trompete 1",
    "Trompete 2",
    "Trompete 3",
    "Trombone 1",
    "Trombone 2",
    "Trompa",
    "Tuba",
    "Bateria",
    "Tímpano",
  ],
  coral: ["Soprano", "Contralto", "Tenor", "Baixo"],
};
